name: GfishBank
version: 1.0.0
description: A Minecraft bank plugin with interest system
author: YourName
main: com.gfish.GFishBank
api-version: 1.21
commands:
  bank:
    description: 银行相关命令
    usage: /bank [deposit/withdraw/balance/help] [amount]
    aliases: [gfishbank, gbank]
permissions:
  gfishbank.use:
    description: 允许使用银行基本功能
    default: true
  gfishbank.admin:
    description: 允许使用银行管理功能
    default: op