name: ZCShop
main: com.gfish.Main
version: 1.0.0
author: GFish
description: 一个简单的商店插件
commands:
  zcshop:
    description: 购买商店物品
    usage: /zcshop <物品名称>
    aliases: [shop, zcs]
permissions:
  zcshop.use:
    description: 允许使用ZCShop命令
    default: true
depend: [Vault]
softdepend: [Essentials]